const clients = [
  {
    'id': 267807,
    'foreign-id': '1111',
    'name': 'google',
    'contact': '',
    'address': {
      'address1': 'googlevägen 1',
      'address2': '',
      'zip-code': '21436',
      'state': '',
      'country': 'Sverige',
    },
    'email': 'test@google.se',
    'country-code': 'SE',
    'currency-code': 'SEK',
    'accountnr': 0,
    'payment-days': 30,
    'orgno': '5555555555',
    'phone': '08123456789',
    'delivery-type': 'Email',
    'vat-nr': '',
    'dimension-entries': {
      'dimension-entries': [
        {
          'id': 393341,
        },
      ],
    },
    'active': true,
  },
  {
    'id': 267807,
    'foreign-id': '1111',
    'name': 'amazon',
    'contact': '',
    'address': {
      'address1': 'amazonvägen 1',
      'address2': 'amazonvägen 2',
      'zip-code': '12345',
      'state': 'malmö',
      'country': 'Sverige',
    },
    'email': 'test@amazon.se',
    'country-code': 'SE',
    'currency-code': 'SEK',
    'accountnr': 0,
    'payment-days': 30,
    'orgno': '5555555555',
    'phone': '08123456789',
    'delivery-type': 'Email',
    'vat-nr': '',
    'dimension-entries': {
      'dimension-entries': [
        {
          'id': 393341,
        },
      ],
    },
    'active': true,
  },
  {
    'id': 267807,
    'foreign-id': '1111',
    'name': 'facebook',
    'contact': '',
    'address': {
      'address1': 'facebookgatan 7',
      'address2': '',
      'zip-code': '',
      'state': '',
      'country': 'Sverige',
    },
    'email': '',
    'country-code': 'SE',
    'currency-code': 'SEK',
    'accountnr': 0,
    'payment-days': 30,
    'orgno': '5555555555',
    'phone': '08123456789',
    'delivery-type': 'Email',
    'vat-nr': '',
    'dimension-entries': {
      'dimension-entries': [
        {
          'id': 393341,
        },
      ],
    },
    'active': true,
  },
  {
    'id': 267807,
    'foreign-id': '1111',
    'name': 'testnet AB',
    'contact': '',
    'address': {
      'address1': 'testvägen 1',
      'address2': 'testvägen 2',
      'zip-code': '',
      'state': 'stockholm',
      'country': 'Sverige',
    },
    'email': 'test@testnet.com',
    'country-code': 'SE',
    'currency-code': 'SEK',
    'accountnr': 0,
    'payment-days': 30,
    'orgno': '5555555555',
    'phone': '08123456789',
    'delivery-type': 'Email',
    'vat-nr': '',
    'dimension-entries': {
      'dimension-entries': [
        {
          'id': 393341,
        },
      ],
    },
    'active': true,
  },
  {
    'id': 267807,
    'foreign-id': '1111',
    'name': 'PE Accounting',
    'contact': '',
    'address': {
      'address1': '',
      'address2': '',
      'zip-code': '',
      'state': '',
      'country': 'Sverige',
    },
    'email': 'test@peaccounting.se',
    'country-code': 'SE',
    'currency-code': 'SEK',
    'accountnr': 0,
    'payment-days': 30,
    'orgno': '5555555555',
    'phone': '08123456789',
    'delivery-type': 'Email',
    'vat-nr': '',
    'dimension-entries': {
      'dimension-entries': [
        {
          'id': 393341,
        },
      ],
    },
    'active': true,
  },
];

module.exports = clients;
